# Site settings
title: John Morrison
email: jjosephmorrison@gmail.com
description: > #
baseurl: "" # the subpath of your site, e.g. /blog/
url: "johnjmorrison.com" # the base hostname & protocol for your site

twitter_username:
github_username: JohnMorrisonn

# Build settings
markdown: kramdown
